# Generated by Django 5.2 on 2025-12-17 19:32

import roman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("closed", models.BooleanField(default=False)),
                ("times", models.JSONField(default=roman.models.Day.day_default)),
            ],
            options={"ordering": ["date"],},
        ),
    ]
