# Generated by Django 5.2 on 2026-01-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roman", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"ordering": ["email"],},
        ),
    ]
