# Generated by Django 5.2 on 2026-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roman", "0002_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numo", models.CharField()),
                ("text", models.CharField()),
            ],
            options={"ordering": ["numo"],},
        ),
    ]
