# Generated by Django 5.2 on 2026-01-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roman", "0003_hometext"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "mainpic",
                    models.ImageField(
                        blank=True, null=True, upload_to="roman/css/userpics"
                    ),
                ),
            ],
            options={"ordering": ["name"],},
        ),
    ]
